[package]
name = "rustcloud-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Core types, errors, and configurations for RustCloud"

[dependencies]
thiserror = { workspace = true }
dotenvy = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
